version: '3.9'

services:
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - ./data:/var/lib/postgres/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  api:
    build:
      context: .
      dockerfile: short_url_api/Dockerfile
    command: >
      sh -c "cd short_url_api &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
